# Yaml config for synthetic motif classification

folds: 5
minority_balance: 0.05
num_seqs:
  - 2000
  - 6000
  - 10000

seq_len:
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 90
  - 100
  - 110
  - 120
  - 130
  - 140
  - 150

# model specifics
models_to_try: 
  #- CNN_simple
  #- 2CNN
  - 2CNN_pool

# training params
lr: 0.0001
epochs: 5000 
patience: 500

# outputs
out_dir: out_synth_cls_10bp_ladder_0.01b